### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by sohvip** [phuvio/tiralabra#1]
*Latasin projektin 18.2. klo 12.*

Projekti vaikuttaa olevan hyvällä mallilla! On hienoa, että ohjelma osaa jopa soittaa generoimaansa musiikkia. Vaikutuin myös siitä, että ohjelmalla on mahdollista generoida polyfonista musiikkia. 

**Kommentteja ja parannusehdotuksia:**
- README:n komentorivitoimintojen alkuun voisi lisätä `poetry install`, sillä se on olennainen komento, kun joku kloonaa projektisi ja haluaa kokeilla sitä.
- `Generate_music`-funktion rivillä 33 on turha `else`, jonka voisi poistaa.
- Luokat `Trie`ja `TrieNode` ovat tällä hetkellä samassa tiedostossa, mutta ne voisi siirtää omiin tiedostoihin selkeyden vuoksi.
- Test.midi-tiedostoa voisi muokata siten, että `test_midi_to_str_to_midi` kävisi myös `string_to_midi`-funktion `elif i.startswith('w')`-haaran läpi, jotta testikattavuus olisi 100%.
- Kun menee valitsemaan midi-tiedostoa, ja painaakin "cancel", niin ohjelma antaa turhan errormessagen. (tämä on vain pieni yksityiskohta ja ohjelman toiminnan kannalta merkityksetön, mutta nostin esiin ihan siltä varalta, että haluat sen korjata).

Tsemppiä loppukurssiin <3

**Comment by phuvio** [comment]
Kiitos hyvistä kommenteista!

**Comment by phuvio** [comment]
- *poetry install' lisätty README:hen ja käyttöohjeeseen
- turha *else* poistettu 'Generate music*-funktiosta
- *TrieNode* muutettu *Trie*:n alaluokaksi
- virheilmoitus poistettu, jos painaa "cancel" midi-tiedostoa avattaessa
