### ISSUE TITLE
Vertaisarviointi #2

### ISSUE THREAD

**Issue by pavezzo** [phuvio/tiralabra#2]
Projekti ladattu 25.2. klo 16.30

Projekti vaikuttaa edistyneen hyvin ja ohjelmakoodi näyttää olevan hyvin jäsenneltyä ja koherenttia.

Muutama parannusehdotus:
- Ohjelma voisi indikoida sen MIDI tiedoston, joka on käyttäjällä auki
- Käytät esim. UI luokan rivillä 75 [:] notaatiota listojen kanssa. Notaatio palauttaa kopion alkuperäisestä listasta, enkä näe sille suoraan syytä tässä tapauksessa. 
- Testikattavuuden saisi 100% kun testaisi string_to_midi funktion elif haaran myös
- Jos haluaa lisätä koodin luettavuutta vielä enemmän voi ottaa käyttöön pythonin typehinttauksen

Onnea loppupalaukseen!

**Comment by phuvio** [comment]
- käyttöliittymä näyttää valitun midi-tiedoston nimen
